- name: Copying Redis repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing Redis
  ansible.builtin.yum:
    name: redis-6.2.11
    state: present    

- name: Updating Visibility
  ansible.builtin.replace:
    path: /etc/redis.conf
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting  Redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes