# Calling Maven role from common role
- name: Calling Maven role from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Execute the maven commands inside roboshop user
  ansible.builtin.shell: mvn clean package &&  mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

# Calling Maven role from common role
- name: Calling CONFIG role from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: config
