- name: Configuring the Nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present 

- name: Creating roboshop user
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop user account

- name: Downloading and Extracting the component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Deleting Files under Roboshop user
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    path: /home/{{APPUSER}}/tarun/
    state: absent

- name: Copying files to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/  
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes    