- name: Demo on conditions
  hosts: test
  tasks:
  vars:
  action: true
   - name: Execute Task when distribution is Centos
     ansible.builtin.debug:
       msg: Welcometo Centos 
     when: ansible_distribution == "CentOS"

   - name: Execute Task when distribution is Ubuntu
     ansible.builtin.debug:
       msg: Welcome to Ubuntu 
     when: ansible_distribution == "Ubuntu"

   - name: Execute about Tarun
     ansible.builtin.debug:
       msg: He is a great Guy
     when: action
      