- name: Demo on conditions
  hosts: test
  tasks:
   - name: Execute Task when distribution is Centos
     ansible.builtin.debug:
       msg: Welcometo Centos 
     when: ansible_distribution == "CentOS"

    - name: Execute Task when distribution is UBUNTU
      ansible.builtin.debug:
        msg: Welcome to UBANTU 
      when: ansible_distribution == "Ubuntu"