- name: Demo on conditions
  hosts: test
  tasks: 
   - name: Check the process is running or not 
     ansible.builtin.shell: psss -ef|grep java 
     ignore_errors: yes

   - name: checking user id
     ansible.builtin.shell: id
     register: OUT

   - name: Execute Task when distribution is Ubuntu
     ansible.builtin.debug:
       msg: "{{OUT}}"

- name: to know how to use facts
  hosts: test
  tasks:
   - name: carrying fron previous playbook
     ansible.builtin.set_fact:
       tarun: "{{OUT.stdout}}"    

   - name: this is to print exit code 
     ansible.builtin.debug:
       msg: "{{out.stdout}}"        
