- name: Demo on conditions
  hosts: test
  tasks: 
   - name: Check the process is running or not 
     ansible.builtin.shell: psss -ef|grep java 
     ignore_errors: yes

   - name: Execute Task when distribution is Ubuntu
     ansible.builtin.debug:
       msg: Welcome to Ubuntu

   - name: checking user id
     ansible.builtin.shell: id
