- name: Demo on conditions
  hosts: test
  tasks: 
   - name: Check the process is running or not 
     ansible.builtin.shell: ps -ef|grep java 

   - name: Execute Task when distribution is Ubuntu
     ansible.builtin.debug:
       msg: Welcome to Ubuntu