- name: play1
  hosts: all
  tasks:
   - name: this is to print first task
     ansible.builtin.debug:
      msg: in this msg we write what msg to print
   - name: this is to print second task
     ansible.builtin.debug:
      msg: in this msg we write what msg to print   