- name: play1
  hosts: all
  vars_files: dev_vars.yaml
  tasks:
   - name: this is to print first task
     ansible.builtin.debug:
       msg: this is first task {{Mark}}
   - name: this is to print second task
     ansible.builtin.debug:
       msg: this is second task {{Peter}}
- name: play1
  hosts: all
  tasks:
   - name: this is to print first task only in dev server
     ansible.builtin.debug:
       msg: this is first task to do on dev server only {{url}}   