- name: This is to know how to use variable from one play to another play
  hosts: all
  tasks:
   - name: this is to execute shell commands
     ansible.builtin.shell: uptime
     register: out
   - name: printing the output of uptime
     ansible.builtin.debug:
       msg: "{{out}}"
   - name: this is to execute shell commands
     ansible.builtin.set_fact:
     status_code: "{{out.r}}"
     ansible.builtin.debug:
       msg: "{{out.stdout}}"       


       