- name: Demo on using variables
  hosts: all
  tasks:
   - name: Demo on using shell module
     ansible.builtin.shell: uptime 
     register: out 
   - name: Showing out variable output
     ansible.builtin.debug:
       msg: "{{out.stdout}}"
   - name: Showing out variable output
     ansible.builtin.debug:
       msg: "{{out.rc}}"       