- name: This is to know how to use variable from one play to another play
  hosts: all
  vars_files:
   files.yaml
  tasks:
   - name: this is to execute shell commands
     ansible.builtin.shell: uptime
     register: out

- name: This is to know how to use variable from one play to another play
  hosts: all
  vars_files:
   files.yaml
  tasks:
   ansible.builtin.set_fact:
     store: files.yaml
   - name: this is to execute shell commands
     ansible.builtin.debug:
       msg: this is {{a}}
        