- name: This is to demonostrate varibles in ansible
  hosts: all
  vars:
   tarun: He has to practice regularlly
  tasks:
   - name: explaining about tarun
     ansible.builtin.debug:
       msg: "{{tarun}}"
    