- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: absent
- name: Downloading and extracting frontend
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes    
 